name: Python package

on: [push]

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Update apt
        run: sudo apt-get update
      - name: Install zip
        run: sudo apt-get install zip
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: 3.12
      - name: Update pip
        run: python -m pip install --upgrade pip
      - name: Install requirements
        run: pip install -r requirements.txt
      - name: Convert notebook to script
        run: jupyter nbconvert PolymerEndLifeApproximation.ipynb --to python
      - name: Run script
        run: python PolymerEndLifeApproximation.py
      - name: Make deploy dir
        run: mkdir deploy
      - name: Move data to deploy
        run: mv polymer_eol_approximate.csv deploy/polymer_eol_approximate.csv
      - name: Build zip
        run: zip deploy.zip -r deploy
      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: deploy
          path: deploy.zip

  deploy:
    name: Deploy
    environment: deploy
    runs-on: ubuntu-latest
    needs: [build]
    if: github.ref == 'refs/heads/main'
    steps:
      - name: Update apt
        run: sudo apt-get update
      - name: Install zip
        run: sudo apt-get install zip
      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: deploy
      - name: Unzip
        run: unzip deploy.zip  
      - name: Upload
        uses: Creepios/sftp-action@v1.0.3
        with:
          host: ${{ secrets.SFTPHOST }}
          port: 22
          username: ${{ secrets.SFTPUSER }}
          password: ${{ secrets.SFTPPASSWORD }}
          localPath: './deploy'
          remotePath: './global-plastics-tool.org/data'
 